### ISSUE TITLE
Traci. exceptions. FatalTracCIError: Could not connect. 

### ISSUE THREAD

**Issue by 17377786473** [seanfhear/mcts-intersections#2]
Hello! I am running this code on my computer and the message 'D: Eclipse Sumo tools trace main. py: 162: UserWarning: Could not connect to TraCI server using port 54246' appears Retrying with different ports

Warnings. warn ("Could not connect to TraCI server using port% s. Retrying with different port."% sumoPort)

Traceback (most recent call last):

File "E: alanechangemethod Monte Carlo Tree Search on Traffic mcts interactions main src main. py", line 140, in<module>

Main()

File "E: alanechangemethod Monte Carlo Tree Search on Traffic mcts interactions main src main. py", line 62, in main

Traci. start (sumOCmd)

File "D: Eclipse Sumo tools track main. py", line 164, in start

Raise FatalTraCIError ("Could not connect.")

Traci. exceptions. FatalTracCIError: Could not connect. 
 I have searched for a lot of information, and both my computer system variables and user variables have been set to sumo.I don't know how to solve this problem.

**Comment by SunTianzhHERE** [comment]
Your file path is wrong in config.xml ,

**Comment by 17377786473** [comment]
May I ask what is wrong and what should be changed?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "seanfhear/mcts-intersections"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月27日(星期四) 晚上9:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [seanfhear/mcts-intersections] Traci. exceptions. FatalTracCIError: Could not connect.  (Issue #2)





 
Your file path is wrong in config.xml ,
